server.port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3333/calculator
    username: springuser
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true